# Generated by Django 3.2.9 on 2021-11-13 11:14

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('norm_factor', models.FloatField()),
                ('image', models.FileField(upload_to='sentinel')),
            ],
            options={
                'verbose_name': 'SentinelData',
                'verbose_name_plural': 'SentinelDatas',
            },
        ),
    ]
