# Generated by Django 3.2.9 on 2021-11-13 11:16

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sentinelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentineldata',
            name='data',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='sentineldata',
            name='image',
            field=models.FileField(default='file.png', upload_to='sentinel'),
        ),
        migrations.AlterField(
            model_name='sentineldata',
            name='norm_factor',
            field=models.FloatField(default=0),
        ),
    ]
